"""
Django settings for Frs project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-@vnbn@fv3kp0p7bzd7bdptrp7n^pd1v(+9@jakr43penk%%@x7"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Allow all hosts for development
ALLOWED_HOSTS = ['*','https://authapp-99adf.web.app',]

# CSRF trusted origins - add your ngrok domain here
CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8000',
    'http://localhost:8000',
    'http://localhost:63322',  # Flutter development server
    'http://192.168.56.1:8000',  # Your computer's IP address
    'http://10.217.232.25:8000',  # Alternative IP address
    'http://10.196.187.25:8000',  # Alternative IP address
    'https://unheaved-elina-roughly.ngrok-free.dev',
      'http://localhost:63414/', 
      'https://authapp-99adf.web.app' # Your ngrok domain
    # Add any other domains you use for testing
]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "face",  # Our face recognition app
    "corsheaders",  # CORS headers for API requests
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # Add this for CORS
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "face.middleware.RoleBasedAccessMiddleware",
    "face.middleware.SecurityHeadersMiddleware",
    "face.middleware.RequestTimingMiddleware",
]

# Allow API requests from Flutter app
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8080",
    "http://127.0.0.1:8080",
    "http://localhost:8000",
    "http://localhost:63322",  # Flutter development server
    "http://10.0.2.2:8000",  # Android emulator
    "http://192.168.56.1:8000",  # Your computer's IP address
    "http://10.217.232.25:8000",  # Alternative IP address
    "http://10.196.187.25:8000", 
   "https://authapp-99adf.web.app",# Alternative IP address
    # Add your computer's IP address for physical device testing
]

CORS_ALLOW_CREDENTIALS = True
# Remove CORS_ALLOW_ALL_ORIGINS for production, but keep it for development
CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = "Frs.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],  # Add templates directory
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "Frs.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Custom user model
AUTH_USER_MODEL = "face.User"

# Custom authentication backends
AUTHENTICATION_BACKENDS = [
    'face.backends.RollNumberBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Login URL
LOGIN_URL = 'face:login'
LOGIN_REDIRECT_URL = 'face:unified_dashboard'

# Email configuration
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "palavalasaanitha1@gmail.com"  # Update with actual email
EMAIL_HOST_PASSWORD = "gbgx yuev vjzu gdyk"  # Update with actual password


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"



USE_I18N = True
TIME_ZONE = "Asia/Kolkata"
USE_TZ = True




# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Media files (uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"