# Generated by Django 4.2 on 2025-11-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("face", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancesession",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
