# Generated by Django 4.2 on 2025-11-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("face", "0002_alter_attendancesession_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="locationconstraint",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="locationconstraint",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="locationconstraint",
            name="radius",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Radius in meters",
                max_digits=5,
                null=True,
            ),
        ),
    ]
