# Generated by Django 4.2 on 2025-11-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("face", "0003_alter_locationconstraint_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="locationconstraint",
            name="radius",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Radius in meters",
                max_digits=10,
                null=True,
            ),
        ),
    ]
