# Generated by Django 4.2 on 2025-11-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("face", "0004_alter_locationconstraint_radius"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="face_image",
            field=models.TextField(blank=True, null=True),
        ),
    ]
