# Generated by Django 4.2 on 2025-11-23 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("face", "0005_user_face_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancesession",
            name="faculty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="faculty_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
