# Generated by Django 4.2 on 2025-11-27 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("face", "0006_attendancesession_faculty"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="department",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="year",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "1st Year"),
                    ("2", "2nd Year"),
                    ("3", "3rd Year"),
                    ("4", "4th Year"),
                ],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="locationconstraint",
            name="radius",
            field=models.DecimalField(decimal_places=2, default=300.0, max_digits=10),
        ),
    ]
