# Generated by Django 4.2 on 2025-11-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("face", "0007_add_year_department_to_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancesession",
            name="target_year",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "1st Year"),
                    ("2", "2nd Year"),
                    ("3", "3rd Year"),
                    ("4", "4th Year"),
                ],
                max_length=1,
                null=True,
            ),
        ),
    ]
