# Generated by Django 4.2 on 2025-11-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("face", "0008_add_target_year_to_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancesession",
            name="target_year",
            field=models.CharField(
                choices=[
                    ("1", "1st Year"),
                    ("2", "2nd Year"),
                    ("3", "3rd Year"),
                    ("4", "4th Year"),
                ],
                default=1,
                max_length=1,
            ),
            preserve_default=False,
        ),
    ]
