# Generated by Django 4.2 on 2025-11-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("face", "0009_alter_attendancesession_target_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancesession",
            name="target_year",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "1st Year"),
                    ("2", "2nd Year"),
                    ("3", "3rd Year"),
                    ("4", "4th Year"),
                ],
                max_length=1,
                null=True,
            ),
        ),
    ]
