# Generated by Django 4.2 on 2025-11-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("face", "0014_remove_attendancesession_target_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancesession",
            name="target_year",
            field=models.CharField(
                choices=[
                    ("1", "1st Year"),
                    ("2", "2nd Year"),
                    ("3", "3rd Year"),
                    ("4", "4th Year"),
                ],
                default=2,
                max_length=1,
            ),
            preserve_default=False,
        ),
    ]
