# Generated by Django 4.2 on 2025-11-28 08:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("face", "0015_attendancesession_target_year"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendancesession",
            name="target_year",
        ),
    ]
