# Generated by Django 4.2 on 2025-11-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("face", "0017_attendancesession_target_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[("UG", "Undergraduate"), ("PG", "Postgraduate")],
                max_length=2,
                null=True,
            ),
        ),
    ]
