# Generated by Django 4.2 on 2025-11-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("face", "0018_user_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancesession",
            name="department",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="attendancesession",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[("UG", "Undergraduate"), ("PG", "Postgraduate")],
                max_length=2,
                null=True,
            ),
        ),
    ]
